default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV.fetch('DB_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { '' } %>
development:
  <<: *default
  database: cinema_subscription_development
test:
  <<: *default
  database: cinema_subscription_test
production:
  <<: *default
  database: cinema_subscription_production
  username: <%= ENV['PRODUCTION_USERNAME'] %>
  password: <%= ENV['PRODUCTION_PASSWORD'] %>
